on: # trigger on push event and main branch to the repo
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch: # must be included in your .yml file for manually triggering event

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: yarn
      - run: yarn build
        env:
          CF_CLIENT_ID: ${{ secrets.CF_CLIENT_ID }}
          CF_CLIENT_SECRET: ${{ secrets.CF_CLIENT_SECRET }}
          STRAPI_API_URL: ${{ secrets.STRAPI_API_URL }}
          STRAPI_TOKEN: ${{ secrets.STRAPI_TOKEN }}
          BASE_URL: ${{ vars.BASE_URL }}
          PRETALX_API_URL: ${{ secrets.PRETALX_API_URL }}
          PRETALX_TOKEN: ${{ secrets.PRETALX_TOKEN }}


      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: bde8664f107f5934b0b7e17cd68e6265
          projectName: selfie-app
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
